### ISSUE TITLE
アタッチを行ったのに音声認識が始まらない

### ISSUE THREAD

**Issue by ghost** [Zeni-Y/UniJulius#1]
インスペクターのspellContainerにScriptableObjectのアタッチをしたのですが、そのあとのPlayボタンを押したときに
DLLNotFoundException: julius-native assembly:\<unknown assembly\> type:\<unknown type\> member:\<null\>
が出てきてしまい、音声認識を実行することが出来ません。どうすればいいですか？

**Comment by Zeni-Y** [comment]
使用しているOS、Unityのバージョン、julius-native.dllファイルの置き場所と設定を教えてください。

現状Windowsにのみ対応しており、DLLNotFoundExceptionは、dllファイルの置き場所を間違えているかOSが異なることが原因だと考えられます。
